### ISSUE TITLE
Protractor 5 and promise manager false?

### ISSUE THREAD

**Issue by appienvanveen** [marcodave/protractor-http-client#10]
Hi,
I'm trying out this lib with protractor 5 and the config: 
 SELENIUM_PROMISE_MANAGER: false

When I run the tests, I get the error:
```
09:43:32] E/launcher - deferred.fulfill is not a function
[09:43:32] E/launcher - TypeError: deferred.fulfill is not a function
    at Request.callback [as _callback] (/home//dev/projects//-drp-e2e/node_modules/protractor-http-client/lib/http-client.ts:46:26)
    at Request.self.callback (/home//dev/projects//-drp-e2e/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/home/dev/projects//-drp-e2e/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/home//dev/projects/drp-e2e/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1090:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

Is there a workaround for this?

**Comment by marcodave** [comment]
hi appienvanveen! unfortunately at the time my library is compatible only with the default promise manager. Another issue, #9 might also be connected to this. At some point I will develop a fox for both. Thanks for understanding!
