### ISSUE TITLE
Not getting correct response

### ISSUE THREAD

**Issue by abhinaba-ghosh** [marcodave/protractor-http-client#12]
Hi,
**I am running below:**

```
const http:HttpClient = new HttpClient("https://httpbin.org");

const response = http.get("/get?param=value");

console.log("response:",response.jsonBody);

expect(response.statusCode).to.be.equal(200);
```

**I am getting below response:**

```
response: JsonPromise {
  wrappedPromise:
   ManagedPromise {
     flow_:
      ControlFlow {
        propagateUnhandledRejections_: true,
        activeQueue_: [TaskQueue],
        taskQueues_: [Set],
        shutdownTask_: null,
        hold_:
         Timeout {
           _called: false,
           _idleTimeout: 2147483647,
           _idlePrev: [TimersList],
           _idleNext: [TimersList],
           _idleStart: 4628,
           _onTimeout: [Function],
           _timerArgs: undefined,
           _repeat: 2147483647,
           _destroyed: false,
           [Symbol(unrefed)]: false,
           [Symbol(asyncId)]: 153,
           [Symbol(triggerId)]: 150 } },
     stack_: null,
     parent_:
      ManagedPromise {
        flow_: [ControlFlow],
        stack_: [Error],
        parent_: null,
        callbacks_: [Array],
        state_: 'pending',
        handled_: true,
        value_: undefined,
        queue_: null },
     callbacks_: null,
     state_: 'pending',
     handled_: false,
     value_: undefined,
     queue_: null } }
(node:22040) UnhandledPromiseRejectionWarning: AssertionError: expected { Object (flow_, stack_, ...) } to equal 200
    at APIMethods.<anonymous> (C:\Dev Room\boiler-plates\serenity-protractor-cucumber-typescript-boilerplate\transform\src\user.interactions\api.interactions\step.functions\api.methods.js:34:56)
    at Generator.next (<anonymous>)
    at C:\Dev Room\boiler-plates\serenity-protractor-cucumber-typescript-boilerplate\transform\src\user.interactions\api.interactions\step.functions\api.methods.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Dev Room\boiler-plates\serenity-protractor-cucumber-typescript-boilerplate\transform\src\user.interactions\api.interactions\step.functions\api.methods.js:3:12)
    at APIMethods.testResponse (C:\Dev Room\boiler-plates\serenity-protractor-cucumber-typescript-boilerplate\transform\src\user.interactions\api.interactions\step.functions\api.methods.js:30:16)
    at Object.<anonymous> (C:\Dev Room\boiler-plates\serenity-protractor-cucumber-typescript-boilerplate\transform\src\user.interactions\api.interactions\step.definitions\api.step.defs.js:22:19)
    at Generator.next (<anonymous>)
    at C:\Dev Room\boiler-plates\serenity-protractor-cucumber-typescript-boilerplate\transform\src\user.interactions\api.interactions\step.definitions\api.step.defs.js:7:71
    at new Promise (<anonymous>)
(node:22040) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:22040) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by marcodave** [comment]
Hi abhinaba1080! It looks like your library that provides the `expect(...)` function does not support promises, probably you need to double check your `package.json`, you might need one more dependency. Can you please share your `dependencies` and `devDependencies` sections of your `package.json`?

**Comment by abhinaba-ghosh** [comment]
@marcodave  Thanks for replying.

Hi my package.json looks like below:
```
{
    "name": "serenity-protractor-cucumber",
    "version": "1.0.0",
    "description": "Serenity.js with Protractor and Cucumber",
    "main": "index.js",
    "scripts": {
        "build": "tsc"
    },
    "author": "Abhinaba Ghosh<abhinaba.ghosh@rsa.com>",
    "license": "Apache-2.0",
    "dependencies": {
        "@types/request": "2.47.0",
        "app-root-path": "^2.2.1",
        "protractor-http-client": "^1.0.4",
        "request": "^2.88.0"
    },
    "devDependencies": {
        "@types/chai": "3.4.34",
        "@types/chai-as-promised": "0.0.29",
        "@types/cucumber": "^4.0.4",
        "@types/node": "^10.7.1",
        "@types/selenium-webdriver": "^3.0.10",
        "basic-auth": "^2.0.0",
        "chai": "3.5.0",
        "chai-as-promised": "5.3.0",
        "chai-smoothie": "^0.2.0",
        "cucumber": "1.3.2",
        "html-dnd": "^1.2.0",
        "lightcrawler": "0.0.9",
        "lighthouse": "5.1.0",
        "npm-failsafe": "^0.4.1",
        "protractor": "5.1.1",
        "rimraf": "2.5.4",
        "serenity-cli": "^0.1.4",
        "serenity-js": "1.10.13",
        "ts-node": "^8.0.2",
        "typescript": "^3.0.1",
        "q": "^1.5.1",
        "request-promise": "^4.2.2"
    }
}
```

My expect library looks like:

```
import chai = require('chai');
import chaiAsPromised = require('chai-as-promised');
import chaiSmoothie=require('chai-smoothie');

chai.use(chaiAsPromised);
chai.use(chaiSmoothie);

export const expect = chai.expect;
```

**Comment by marcodave** [comment]
Thank you. According to documentation at https://www.npmjs.com/package/chai-as-promised, try with `expect(response.statusCode).to.eventually.be.equal(200);`

**Comment by abhinaba-ghosh** [comment]
> Thank you. According to documentation at https://www.npmjs.com/package/chai-as-promised, try with `expect(response.statusCode).to.eventually.be.equal(200);`

@marcodave  , the issue is not with the expect, the real problem is I am not receiving proper response. Suppose, I want to log the status code, I have written :

```
const http:HttpClient = new HttpClient("https://httpbin.org");

        const response = http.get("/get?param=value");
        console.log("response code:",response.statusCode);
```

The output i am getting is : 

```
response code: ManagedPromise {
  flow_:
   ControlFlow {
     propagateUnhandledRejections_: true,
     activeQueue_:
      TaskQueue {
        name_: 'TaskQueue::190',
        flow_: [Circular],
        tasks_: [Array],
        interrupts_: null,
        pending_: null,
        subQ_: null,
        state_: 'new',
        unhandledRejections_: Set {} },
     taskQueues_: Set { [TaskQueue] },
     shutdownTask_: null,
     hold_:
      Timeout {
        _called: false,
        _idleTimeout: 2147483647,
        _idlePrev: [TimersList],
        _idleNext: [TimersList],
        _idleStart: 27361,
        _onTimeout: [Function],
        _timerArgs: undefined,
        _repeat: 2147483647,
        _destroyed: false,
        [Symbol(unrefed)]: false,
        [Symbol(asyncId)]: 169,
        [Symbol(triggerId)]: 166 } },
  stack_: null,
  parent_:
   ManagedPromise {
     flow_:
      ControlFlow {
        propagateUnhandledRejections_: true,
        activeQueue_: [TaskQueue],
        taskQueues_: [Set],
        shutdownTask_: null,
        hold_:
         Timeout {
           _called: false,
           _idleTimeout: 2147483647,
           _idlePrev: [TimersList],
           _idleNext: [TimersList],
           _idleStart: 27361,
           _onTimeout: [Function],
           _timerArgs: undefined,
           _repeat: 2147483647,
           _destroyed: false,
           [Symbol(unrefed)]: false,
           [Symbol(asyncId)]: 169,
           [Symbol(triggerId)]: 166 } },
     stack_:
      { Task: <anonymous>
          at HttpClient.request (C:\Dev Room\boiler-plates\serenity-protractor-cucumber-typescript-boilerplate\node_modules\protractor-http-client\lib\http-client.ts:49:48)
          at HttpClient.send (C:\Dev Room\boiler-plates\serenity-protractor-cucumber-typescript-boilerplate\node_modules\protractor-http-client\lib\http-client.ts:85:21)
          at HttpClient.get (C:\Dev Room\boiler-plates\serenity-protractor-cucumber-typescript-boilerplate\node_modules\protractor-http-client\lib\http-client.ts:56:21)
          at APIMethods.<anonymous> (C:\Dev Room\boiler-plates\serenity-protractor-cucumber-typescript-boilerplate\transform\src\user.interactions\api.interactions\step.functions\api.methods.js:30:35)
          at Generator.next (<anonymous>)
          at C:\Dev Room\boiler-plates\serenity-protractor-cucumber-typescript-boilerplate\transform\src\user.interactions\api.interactions\step.functions\api.methods.js:7:71
          at new Promise (<anonymous>)
          at __awaiter (C:\Dev Room\boiler-plates\serenity-protractor-cucumber-typescript-boilerplate\transform\src\user.interactions\api.interactions\step.functions\api.methods.js:3:12)
          at APIMethods.testResponse (C:\Dev Room\boiler-plates\serenity-protractor-cucumber-typescript-boilerplate\transform\src\user.interactions\api.interactions\step.functions\api.methods.js:28:16)
          at Object.<anonymous> (C:\Dev Room\boiler-plates\serenity-protractor-cucumber-typescript-boilerplate\transform\src\user.interactions\api.interactions\step.definitions\api.step.defs.js:22:19) name: 'Task' },
     parent_: null,
     callbacks_: [ [Task] ],
     state_: 'pending',
     handled_: true,
     value_: undefined,
     queue_: null },
  callbacks_: null,
  state_: 'pending',
  handled_: false,
  value_: undefined,
  queue_: null }
```

I should have got 200/400.. whatever, but it should have been a status code.  Do i need to include some configuration? 

Let me know if i need to add some proxy/something.

**Comment by abhinaba-ghosh** [comment]
I got the solution finally :)
```
const http = new HttpClient("https://httpbin.org);

    const  userGetResponse: ResponsePromise= http.get("/get?param=value");
    await userGetResponse.stringBody.then(jsonString => {
        console.log("result:",jsonString);
        
      });
```
