### ISSUE TITLE
TypeError: protractor.promise.controlFlow is not a function

### ISSUE THREAD

**Issue by davedalselv** [marcodave/protractor-http-client#9]
My project can't compile because of the following error:

```
[dev] [14:14:13] E/launcher - Error: TypeError: protractor.promise.controlFlow is not a function
[dev]     at Object.<anonymous> (C:\Protractor\magazin-admin-cucumber\node_modules\protractor-http-client\lib\http-client.ts:9:72)
[dev]     at Module._compile (module.js:652:30)
[dev]     at Object.Module._extensions..js (module.js:663:10)
[dev]     at Module.load (module.js:565:32)
[dev]     at tryModuleLoad (module.js:505:12)
[dev]     at Function.Module._load (module.js:497:3)
[dev]     at Module.require (module.js:596:17)
[dev]     at require (internal/module.js:11:18)
```

Versions:
```
"protractor": "^6.0.0",
"protractor-http-client": "^1.0.4",
"typescript": "^3.3.4000",
```

**Comment by marcodave** [comment]
hi! thanks for the submission.
I checked the Protractor 6.0.0 changes, Apparently they got rid of the controlFlow mechanics from WebDriver, [relevant commit from protractor](https://github.com/angular/protractor/commit/e22065ca6c91c6f49f9bbebcdc6351bdeb6e61ec#diff-82125c42d99198448810001f71b37d99)

I see two possible solutions, if you really need the http-client
- stick with protractor 5.x which still makes use of controlFlow()
- modify protractor-http-client to be compatible with 6.0.0, (and figure out retrocompatibility)
